name: Call consume repository

on:
  push:
    branches: ["main"]

env:
  POKEMON: ${{ secrets.POKEMON }}
  LEVEL: ${{ secrets.LEVEL }}

jobs:
  build:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Dispatch"
        uses: QuasarwayGit/workflow-consume@main
        with:
          client-payload: |-
            {
              "POKEMON": "${{ env.POKEMON }}",
              "LEVEL": "${{ env.LEVEL }}"
            }
